### PR TITLE
Trim back the website to remove any dated information

### PR DESCRIPTION
**Pull request by tclose**
* updates the Gemfile so that the bundle can be served with Ruby 3
* Reworked menu to move references to dated material to less prominent places
* Added events for past and previous BrainHack Globals

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Thanks for doing this @tclose. I'm finding it hard to review some parts, would it be possible:
- To add a body to the commits so that they get some description?
- To split commits into with different commits so that they contain only one relevant change, e.g. change the layout vs. add content? e.g. ef1f7b61416bfdaac5d9ceb55d2ca5dff09884be
- To know how does the new website look like?
- To know what dated information was removed ef1f7b61416bfdaac5d9ceb55d2ca5dff09884be? I've compared the removed lines and the added ones, and there seems to be no removal in that commit?
- To  know where was this information transferred to 4986c563d0391183b13332e000a6e94e27770e7d, especially the links to the proceedings?

**Comment by tclose** [comment]
Ok, I have rebased the PR to clean it up a bit and split a couple of commits

> * To add a body to the commits so that they get some description?

Which commits need more description? Is it a bit easier to follow them now?

> * To split commits into with different commits so that they contain only one relevant change, e.g. change the layout vs. add content? e.g. [ef1f7b6](https://github.com/brainhackorg/brainhackorg.github.io/commit/ef1f7b61416bfdaac5d9ceb55d2ca5dff09884be)

I have split up [c822bcd](https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits/c822bcd8342982e73e644f00709fd208fe567757)]

> * To know how does the new website look like?

Much the same, here is a screen shot of the rearranged home page (the style is unchanged)

Screen Shot 2024-09-13 at 9 45 44 am

Are you able to install the dev env to have a look at it interactively (i.e.install Ruby and then `bundle install` and `bundle exec jekyll serve`)?

> * To know what dated information was removed [ef1f7b6](https://github.com/brainhackorg/brainhackorg.github.io/commit/ef1f7b61416bfdaac5d9ceb55d2ca5dff09884be)? I've compared the removed lines and the added ones, and there seems to be no removal in that commit?

[c822bcd](https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits/c822bcd8342982e73e644f00709fd208fe567757): Moves the old posts into the ARCHIVE menu item 

[ec6f180](https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits/ec6f1805cd395e2449c47e99a65b7efd373b4122): deletes dated proceedings and outcomes from the about page.

> * To  know where was this information transferred to [4986c56](https://github.com/brainhackorg/brainhackorg.github.io/commit/4986c563d0391183b13332e000a6e94e27770e7d), especially the links to the proceedings?

It is now under the ARCHIVE menu item

**Comment by tclose** [comment]
Do you know who the current board members are (if the board still exists in practice)?

**Comment by jhlegarreta** [comment]
Is there a reason why the following commit uses ".markdown" instead of ".md" as the file extension?
https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits/16479425b7be6bfe08c3eceb61592d1d5c06f0d8

I guess removing the projects in the `Brainhack Outcomes` section is reasonable as they are several years old, but the publications should be linked from somewhere IMO:
https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits/ec6f1805cd395e2449c47e99a65b7efd373b4122

> Which commits need more description?

If you click on each commit https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits you will see that none of them has a commit message body, only a subject, some being cut due to excessive line length, etc.

e.g. efdb42c603a4c0b2ac13af1ebf2e0ce8be597be6 does more than renaming a file. Adding a commit message gives ample space to provide the necessary details about the change.

> Is it a bit easier to follow them now?

It is.

> Much the same, here is a screen shot of the rearranged home page (the style is unchanged)

OK.

> Are you able to install the dev env to have a look at it interactively (i.e.install Ruby and then bundle install and bundle exec jekyll serve)?

Have not tried Tom, sorry. I do not have the bandwidth now.

> Do you know who the current board members are (if the board still exists in practice)?

I don't Tom, sorry. I have not been active lately in the Brainhacks.

**Comment by tclose** [comment]
> Is there a reason why the following commit uses ".markdown" instead of ".md" as the file extension? [1647942](https://github.com/brainhackorg/brainhackorg.github.io/commit/16479425b7be6bfe08c3eceb61592d1d5c06f0d8)

I was just following the style of the other posts

> I guess removing the projects in the `Brainhack Outcomes` section is reasonable as they are several years old, but the publications should be linked from somewhere IMO: [ec6f180](https://github.com/brainhackorg/brainhackorg.github.io/commit/ec6f1805cd395e2449c47e99a65b7efd373b4122)

They are still accessible from the ARCHIVE menu on the home page. I can add them back in but having the last one showing up from 5 years ago on the About page gives the impression the org is dead IMO.

> > Which commits need more description?
> 
> If you click on each commit https://github.com/brainhackorg/brainhackorg.github.io/pull/35/commits you will see that none of them has a commit message body, only a subject, some being cut due to excessive line length, etc.

I have never written a commit body in 15 years, is it necessary when you have the diffs?

> e.g. [efdb42c](https://github.com/brainhackorg/brainhackorg.github.io/commit/efdb42c603a4c0b2ac13af1ebf2e0ce8be597be6) does more than renaming a file. Adding a commit message gives ample space to provide the necessary details about the change.

It renames the file, the corresponding title of the page, and adds a link to the mattermost channel. Do I have to spell out every minor change? Isn't the final state the most important?

> > Are you able to install the dev env to have a look at it interactively (i.e.install Ruby and then bundle install and bundle exec jekyll serve)?
> 
> Have not tried Tom, sorry. I do not have the bandwidth now.

I also have very little bandwidth. I'm just trying to get this fixed as it looked like it needed doing.

> > Do you know who the current board members are (if the board still exists in practice)?
> 
> I don't Tom, sorry. I have not been active lately in the Brainhacks.

I'm getting the impression that no one really has.

**Comment by crnolan** [comment]
* Brainhack Global 2024 banner on front page has "Hybird" rather than "Hybrid"
* Promote a project or event: "Mattermost channel" is a bit orphaned there with no explanation - it should be a bullet point and possibly a little explanation "Many Brainhack events choose to communicate via the Brianhack Mattermost server; join here and create a channel for your event."

**Comment by crnolan** [comment]
Perhaps the mattermost server could be linked on the About page as well, but can easily be done later.

**Comment by tclose** [comment]
I believe these issues have been addressed now so will merge the changes in

**Pull request merged**
