### PR TITLE
ENH: Match site BHG 2019 banner with BHG 2019 site banner

### PR DESCRIPTION
**Pull request by jhlegarreta**
Match site BHG 2019 banner with BHG 2019 site banner.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@anibalsolon I thought that matching the `brainhack` site's banner preview of the BHG 2019 would be appropriate. Feel free to modify the picture if you think of better ways (e.g. remove the paragraph and just use the brain picture and the background gradient along with the dates) to do this.

**Comment by anibalsolon** [comment]
thanks @jhlegarreta

**Comment by jhlegarreta** [comment]
@anibalsolon Well, looks like its effect was not the expected one in the global website:
http://www.brainhack.org/

Although the BHG 2019 space seems to be OK:
http://www.brainhack.org/2019/11/13/global2019.html

Can we reset?

Is there something missing to the commit to restrict the size? I though it was the canvas that managed that automatically.

**Comment by anibalsolon** [comment]
Thank you for letting me know @jhlegarreta I've fixed the size. I thought it would resize it too.

**Pull request merged**
